### ISSUE TITLE
We at Sandstorm like your app!

### ISSUE THREAD

**Issue by neynah** [anherrera/budget#17]
Hi @anherrera!

I'm the designer at [sandstorm.io](http://sandstorm.io) and discovered your app through Made with Meteor. It seems really useful and I thought it'd be a great fit for Sandstorm. We're currently looking for unique open-source apps to add to our [App Market](https://apps.sandstorm.io/) and we don't have any budgeting/finance apps so this would definitely be great for our community.

Would you possibly be interested in helping me get your app running on Sandstorm so that others can quickly install & create instances of it? I was able to package it successfully but perhaps you'd like to [test it out on Sandstorm](https://oasis.sandstorm.io/appdemo/3hrzumm7nx9ed81hgn1hjkv37c8asmfs9yad3jttzcrh8gkjsyj0) to see if it works as you want it to.

I'm pretty excited about this so if you decide you are interested in polishing this, I'd be happy to design some icons/graphics for you. Let me know if you have any ideas.

Cheers! :)

**Comment by anherrera** [comment]
Hi @neynah,

I'm interested! The only thing is, I built this pretty much for myself, so there's still a few bugs / kinks to work out and I think more information to be added since it works a lot differently from most other budget apps you see around (hence, my need to build it). 

Instead of just putting in estimated numbers for expenses for each month, my app is more focused on the day-to-day of budgeting. I started getting really frustrated with other apps because I was being paid bi-weekly but all my bills were on a monthly basis, and bills were due at different times of the month. So what my app does is let a user input their bills and income manually (this can be a positive, or a negative) and track how much money they'll have by the day. 

Some drawbacks to this though is if someone isn't always sure when a bill is due (say you get charged anywhere from the 16th - 20th) and they put it as the 16th, then they check the app on the 18th but haven't been charged for that bill yet, they might forget to account for that when entering their "current" balance. So it's a little easy sometimes to mess up, but of course my app isn't going to come with any guarantees. 

Let me know if this all still sounds good to you. There's a few things I need to fix still, if I blow the dust off this project and get back into it. 

Thanks!

**Comment by neynah** [comment]
Hi @anherrera!

I can see that that the date range issue for billing can be problematic. Overall, I still think the app is still quite useful!

What are some of the things you'd like to fix before you'd be happy to publish your app? (Keep in mind that you can continue to develop it and publish new versions as well.) If you're open to suggestions, we're currently trying out your app and could probably make small recommendations.

We'll offer as much support as we can for packaging & design.  I'm happy to get started on some graphics soon if you have any ideas for that. :)

**Comment by anherrera** [comment]
Hi, 

I think the date range selection is a bit wonky sometimes. I have to make it consistent on making sure the dates selected are INCLUSIVE rather than exclusive. I think that's my biggest annoyance at the moment.

I also have intermittent issues where editing 2 in a row or editing and then creating doesn't clear the fields out all the way, so I gotta take a gander at that. 

I'm totally open to suggestions. You can even submit them as issues if you'd like. 

I'm not much of a designer, so I basically just cobbled it together with Bootstrap 3, ha. I'm open to suggestions. 

Thanks!

**Comment by simonv3** [comment]
Hey @anherrera, I was looking for an app like this to run on Sandstorm, and Asheesh on #sandstorm pointed me this way. 

What I like about Sandstorm is that the app framework very much enables [dogfooding](http://indiewebcamp.com/dogfood) - ie, you build what you want, nevermind what other people want. If someone else wants another budgeting app then they can build one!

I'm a Meteor developer myself as well, so happy to help out with small things here and there.

Mind if I add your app here: https://oasis.sandstorm.io/grain/LJtu6b8tbHruommKY5ZyEu/?

**Comment by anherrera** [comment]
Heya, I don't have access to the grain linked, but I'm curious how it all works. Do I just add the files for sandstorm and the app is live on the service?

**Comment by paulproteus** [comment]
Hi @anherrera !

You can use this link to access the grain that Simon linked-to: https://oasis.sandstorm.io/shared/xEMnW7pA5gkXu99uzu4tQuGyekoqXItY-qr-77Zs6lm

As for how it all works, here's a quick overview:

- You add the files for Sandstorm, and you (or simonv3) test on your own computer.

- You use our dev tools on your own computer to turn your app into a `*.spk` file.

- You use our dev tools on your own computer to upload that `*.spk` file to the Sandstorm app market.

- Then it's live on the app market.

Once it's live on the app market, people install it by:

- Visiting their own Sandstorm servers, wherever they are

- Clicking a `+` icon to install a new app

- Finding your app in the market

- Clicking "Install"

And then they can use it on their own Sandstorm server.

In this sense, it's very similar to a mobile app marketplace.

I hope that helps. Let me know if you have other questions!

**Comment by simonv3** [comment]
Sorry, totally forgot to get the sharing link, instead of the normal link. 

Just want to add that the Sandstorm folks have made it very easy to package Meteor apps.

**Comment by simonv3** [comment]
@neynah, do you have the code showing the changes that you made of the packaged app somewhere on GitHub so that @anherrera can see what those changes entail?

**Comment by neynah** [comment]
@simonv3 The specific code chcanges I made are here: https://github.com/neynah/budget/commit/a0d206ec21dd19384b344ff0e05f3c2ec3b7e171

Majority of the changes were automated using our automated Meteor packaging tool. I followed these instructions: https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial-meteor/

@anherrera basically I took your app at the time and ran it through the packer and tested the .spk file that it produced. I believe your app is currently in a state where it's very close to being ready for the App Market. Here's the link again if you'd like to test it out: https://oasis.sandstorm.io/appdemo/3hrzumm7nx9ed81hgn1hjkv37c8asmfs9yad3jttzcrh8gkjsyj0

Before packaging it with our tool, I would suggest:
- removing the login name/link since you'll see that Sandstorm handles that
- poke around and make sure the app works as it should
- provide me with feedback on https://github.com/anherrera/budget/issues/19 so I can design a nice icon for your app!

Let any of us know if you need some help/have further questions. :)

**Comment by ocdtrekkie** [comment]
I would use this as a Sandstorm app. I actually currently do keep my checkbook's paper register next to my computer desk. :P

**Comment by anherrera** [comment]
Hey, I removed the login buttons from the header. My question is, usually I require some type of login for the app to work (and so users can come back and still have all the stuff they added tied to their userId). Would sandstorm handle userId's instead? 

Thanks

**Comment by ocdtrekkie** [comment]
You probably don't want to remove the login buttons from non-Sandstorm users. I see you're using accounts-google and accounts-github for login. What you can do instead of just removing the button, is to add accounts-sandstorm: https://atmospherejs.com/kenton/accounts-sandstorm

So basically, rather than someone logging in with GitHub or Google, when they open the app inside Sandstorm, it'll use the Sandstorm account.

**Comment by simonv3** [comment]
This is actually the hardest part to decide on I think. You can make a decision to maintain two version of the app - one uses Sandstorm to log in (kenton's accounts-sandstorm package will automatically log a user in using their sandstorm credentials, which is why @neynah suggested above to remove the log in button, her fork already uses the accounts-sandstorm package), and one that uses the standard Meteor log in version.

You can try to do both in one app where you use if statements to check whether the app is running in Sandstorm or not. If it's not, show the normal log in button. If it is, let Sandstorm do it's thing for logging in. But like @kentonv has pointed out in accounts-sandstorm development, **that's not super secure** (because you can inject sandstorm's headers to pretend to be a normal user).

Because all you're doing in this app is just logging a user in, keeping a fork of the "non-sandstorm" app  might be manageable - someone will just have to pull in whatever changes you make to the app and to keep the package up to date with live development on this branch. You'd just want to make sure that the two branches don't diverge too much (or if you don't care, they can diverge!)

Ultimately it's your app, so it's up to you! I suspect you'd get a lot of people interested in your app using it through Sandstorm since you'd be the first one of its kind in the app store, and probably a couple of people contributing to the development here as well!

**Comment by paulproteus** [comment]
As an addendum to what @simonv3 said: Once https://github.com/sandstorm-io/meteor-accounts-sandstorm/pull/20 lands, then the header injection issue goes away.

**Comment by kentonv** [comment]
With accounts-sandstorm 0.3.0, accounts-sandstorm will only activate itself if the `SANDSTORM` environment variable is set on the server, so it's now safe to include in both builds. Moreover, when `SANDSTORM` *is* set, accounts-sandstorm will automatically disable other account packages, so that again it's safe to include them in both builds.

You can also now use `if (__meteor_runtime_config__.SANDSTORM)` to check if you're running in Sandstorm and then hide your login buttons.

**Comment by anherrera** [comment]
Hey guys, 

Did some housekeeping updating meteor to 1.3 and I also have the app running on Heroku. 

Can you guys try it out on sandstorm again and see if it's good to go or needs more tweaking? 

Thanks.

**Comment by anherrera** [comment]
Hello from the future! 

Please check out https://github.com/anherrera/budget-redo for my 2022 version of this app.

**Comment by ocdtrekkie** [comment]
Hey @anherrera, it has indeed been a long time, but I think this would still be pretty cool. I will go follow your new project.
